
app = "redux-anecdotes-pipeline"

[build]

[env]
  port = "3001"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
