
app = "redux-anecdotes-pipeline"

[build]

[deploy]
   strategy = "canary"

[env]
  port = "3001"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "1m"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"